name: "Kompot publish"

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    #Remove when workflow_dispatch trigger is removed
    #if: contains(github.ref, 'kompot')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt-hotspot'
      #Decode key ring file from secrets and put it to ~/.gradle/
      - name: Decode
        shell: bash
        run: 'echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" | base64 -d > secring.gpg'
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: :kompot:publish -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{ secrets.SIGNING_PASSWORD }} -Psigning.secretKeyRingFile=../secring.gpg
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}